name: release
on:
  push:
    tags:
      - v*
jobs:

  release_debian_image_prod:
    runs-on: ubuntu-latest
    env:
      CONTAINER_REPO: "wlieberz/release-notifier-rust"
      BASE_IMG: "debian-12-bookworm-slim"
      DOCKERFILE: "Dockerfile.debian-slim"
    steps:
      - uses: actions/checkout@v4

      - name: Docker Build and Tag
        run: docker build --file ${DOCKERFILE} --tag ${CONTAINER_REPO}:${GITHUB_REF_NAME}-${BASE_IMG} ./

      - name: DockerHub Login
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: echo $DOCKERHUB_TOKEN | docker login --username wlieberz --password-stdin

      - name: Docker Push
        run: docker push ${CONTAINER_REPO}:${GITHUB_REF_NAME}-${BASE_IMG} 

      - name: DockerHub Logout
        run: docker logout

  release_alpine_image_prod:
    runs-on: ubuntu-latest
    env:
      CONTAINER_REPO: "wlieberz/release-notifier-rust"
      BASE_IMG: "alpine-3.18.3"
      DOCKERFILE: "Dockerfile.alpine"
    steps:
      - uses: actions/checkout@v4

      - name: Docker Build and Tag
        run: docker build --file ${DOCKERFILE} --tag ${CONTAINER_REPO}:${GITHUB_REF_NAME}-${BASE_IMG} ./

      - name: DockerHub Login
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: echo $DOCKERHUB_TOKEN | docker login --username wlieberz --password-stdin

      - name: Docker Push
        run: docker push ${CONTAINER_REPO}:${GITHUB_REF_NAME}-${BASE_IMG} 

      - name: DockerHub Logout
        run: docker logout